meta:
  environment: (( merge ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: vault_z1
    instances: 1
    networks:
      - name: vault1
    persistent_disk: (( meta.persistent_disk ))

compilation:
  cloud_properties:
    instance_type: m3.medium

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks: (( merge ))
